-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 21:20:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ADMINISTRADOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ADMINISTRADOR` ;

CREATE TABLE IF NOT EXISTS `ADMINISTRADOR` (
  `idAdm` INT NOT NULL,
  `emailAdm` VARCHAR(45) NOT NULL,
  `userAdm` VARCHAR(30) NOT NULL,
  `nomeAdm` VARCHAR(20) NOT NULL,
  `sobrenomeAdm` VARCHAR(45) NOT NULL,
  `celularAdm` VARCHAR(11) NOT NULL,
  `idadeAdm` INT NOT NULL,
  PRIMARY KEY (`idAdm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ALUNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUNO` ;

CREATE TABLE IF NOT EXISTS `ALUNO` (
  `idALUNO` INT NOT NULL,
  `emailALUNO` VARCHAR(45) NOT NULL,
  `userALUNO` VARCHAR(30) NOT NULL,
  `nomeALUNO` VARCHAR(20) NOT NULL,
  `sobrenomeALUNO` VARCHAR(45) NOT NULL,
  `celularALUNO` VARCHAR(11) NOT NULL,
  `idadeALUNO` INT NOT NULL,
  PRIMARY KEY (`idALUNO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ASSISTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ASSISTE` ;

CREATE TABLE IF NOT EXISTS `ASSISTE` (
  `idALUNO` INT NOT NULL,
  `idAULA` INT NOT NULL,
  CONSTRAINT `idALUNO`
    FOREIGN KEY (`idALUNO`)
    REFERENCES `ALUNO` (`idALUNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAULA`
    FOREIGN KEY (`idALUNO` , `idAULA`)
    REFERENCES `AULA` (`idAULA` , `idAULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FOREIGN KEYS` ON `ASSISTE` (`idALUNO` ASC, `idAULA` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `AULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AULA` ;

CREATE TABLE IF NOT EXISTS `AULA` (
  `idAULA` INT NOT NULL,
  `nomeAULA` VARCHAR(45) NOT NULL,
  `duracao` DATETIME NOT NULL,
  PRIMARY KEY (`idAULA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GERENCIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GERENCIA` ;

CREATE TABLE IF NOT EXISTS `GERENCIA` (
  `idADMIN` INT NOT NULL,
  `idAULA` INT NOT NULL,
  CONSTRAINT `idAULA`
    FOREIGN KEY (`idAULA` , `idADMIN`)
    REFERENCES `AULA` (`idAULA` , `idAULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idADM`
    FOREIGN KEY (`idAULA`)
    REFERENCES `ADMINISTRADOR` (`idAdm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FOREIGN KEY` ON `GERENCIA` (`idAULA` ASC, `idADMIN` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
